language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install forbesqotd; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then pip3 install forbesqotd; fi
# command to run tests
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then cd test2; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then cd test3; fi
  - python -m unittest discover