language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
  - python setup.py install
  - pip install pytest
# command to run tests
script:
  - cd test2
  - python -m unittest discover
  - cd ../test3
  - python3 -m unittest discover